[project]
name = "polydash-etl"
version = "0.1.0"
description = "etl for polydash app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=6.30.1",
    "psycopg2>=2.9.11",
    "requests>=2.32.5",
]
